import Head from "next/head";
// import { Inter } from 'next/font/google'
import styles from "@/styles/Home.module.css";
import Button from "@/components/Button";
import HeaderLinks from "@/components/HeaderLinks";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderLinks />
        <div className={styles.header}>
          <span>(By skv1k)</span>
          <h1>Портфолио</h1>
          <p>Дизайн- это эстетичность и красота</p>
        </div>
      </main>
    </>
  );
}
